doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        driver: "%env(resolve:DATABASE_DRIVER)%"
        host: "%env(resolve:DATABASE_HOST)%"
        port: "%env(resolve:DATABASE_PORT)%"
        dbname: "%env(resolve:DATABASE_DBNAME)%"
        user: "%env(resolve:DATABASE_USER)%"
        password: "%env(resolve:DATABASE_PASSWORD)%"
        logging: true
        options:
          Encrypt: true
          TrustServerCertificate: true
  #            misdb :
  #                url: '%env(resolve:DATABASE_URL)%'
  # IMPORTANT: You MUST configure your server version,
  # either here or in the DATABASE_URL env var (see .env file)
  #server_version: '13'
  orm:
    dql:
      string_functions:
        DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
        JSON_CONTAINS: DoctrineExtensions\Query\Mysql\JsonContains
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        dir: "%kernel.project_dir%/src/Entity"
        prefix: 'App\Entity'
        alias: App
        type: attribute

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: "_test%env(default::TEST_TOKEN)%"

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
